### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by alexmyczko** [alexmyczko/modplug-tools#1]
when -ao wav is used, there's no need to open/close the sound device
also the interactive mode is not necessary, and its output is wrong.

a -i (display info) mode would be nice

wav renderer should create inputfilename.wav and check if it's already there (multi file rendering, only the last results gets stored as output.wav currently)

**Comment by Konstanty** [comment]
Thanks, libAO is working on MacOS for me

**Comment by alexmyczko** [comment]
can confirm: https://github.com/alexmyczko/homebrew-mac
